### ISSUE TITLE
Reading data from files - formulering

### ISSUE THREAD

**Issue by enerammer** [KUBDatalab/R-toolbox#157]
Formulering ’ As mentioned above the package haven can read SAS-files:’ – jeg kan ikke finde at det er nævnt tidligere at haven pakken kan læse SAS-files

**Comment by chrbknudsen** [comment]
Hov! Ja...

**Comment by chrbknudsen** [comment]
Njarh. Det nævnes i en parentes under spss. Det ændrer ikke rigtig på pointen.
